#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
articles_path = ROOT / "content" / "articles" / "articles.json"
products_path = ROOT / "data" / "products.json"
links_path = ROOT / "data" / "affiliate_links.json"

articles = json.loads(articles_path.read_text(encoding="utf-8"))
products = json.loads(products_path.read_text(encoding="utf-8"))
links = json.loads(links_path.read_text(encoding="utf-8"))
existing = {a["slug"] for a in articles}
product_ids = {p["id"] for p in products}

new_products = [
    {"id":"door-window-sensor","name":"Dörr- och fönstersensor","category":"sensorer","price_hint":"10–30 €","best_for":"ytterdörr, balkongdörr, kylskåp och fönster","note":"Bra när du vill veta om något lämnats öppet, inte bara om någon rör sig i rummet."},
    {"id":"temperature-sensor","name":"Temperatur- och fuktsensor","category":"klimat","price_hint":"10–35 €","best_for":"barnrum, badrum, källare och tvättstuga","note":"Mest användbar när värdet leder till en enkel handling: vädra, slå på fläkt eller flytta avfuktare."},
    {"id":"zigbee-hub","name":"Zigbee-hubb","category":"hubb","price_hint":"25–120 €","best_for":"stabilare knappar, lampor och sensorer","note":"Välj hubb efter vilka prylar du vill använda, inte bara efter lägsta pris."},
    {"id":"smart-thermostat","name":"Smart termostat / elementstyrning","category":"värme","price_hint":"30–100 €","best_for":"jämnare temperatur i sovrum och hemmakontor","note":"Börja med ett rum där temperaturen faktiskt skapar problem."},
]
for p in new_products:
    if p["id"] not in product_ids:
        products.append(p)
        product_ids.add(p["id"])

links.setdefault("door-window-sensor", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=zigbee+d%C3%B6rrsensor&tag=smartahemmet-21","label":"Se dörrsensorer på Amazon","target_pages":[]})
links.setdefault("temperature-sensor", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=zigbee+temperatursensor+fuktsensor&tag=smartahemmet-21","label":"Se temperatur- och fuktsensorer på Amazon","target_pages":[]})
links.setdefault("zigbee-hub", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=zigbee+hubb+home+assistant&tag=smartahemmet-21","label":"Se Zigbee-hubbar på Amazon","target_pages":[]})
links.setdefault("smart-thermostat", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=smart+termostat+zigbee&tag=smartahemmet-21","label":"Se smarta termostater på Amazon","target_pages":[]})

def article(slug, title, description, category, products, tags, intro, examples, sections):
    return {
        "slug": slug,
        "title": title,
        "description": description,
        "category": category,
        "products": products,
        "tags": tags,
        "intro": intro,
        "examples": examples,
        "sections": sections + [
            ["Så märker du att det hjälper", "Lösningen ska märkas i vardagen utan att någon behöver prata om tekniken. Färre avbrott, färre missade saker och mindre letande är bättre mål än en perfekt dashboard."],
            ["Vanligt misstag", "Bygg inte runt undantagsdagen. Börja med det som händer flera gånger i veckan och gör lösningen så enkel att den fungerar även när alla är trötta."],
        ],
    }

new_articles = [
article("basta-dorrsensorer-for-smart-hem", "Bästa dörrsensorer för smart hem", "Dörr- och fönstersensorer för hall, balkong, kylskåp och barnsäkerhet.", "köpguide", ["door-window-sensor", "smart-button"], ["kopguide","sensorer","dorrar","hall"], "En dörrsensor är enkel, billig och ofta mer användbar än den låter. Den säger inte bara om en dörr är öppen, utan kan starta en rutin, varna om balkongdörren står på glänt eller påminna när kylskåpet inte stängts ordentligt.", ["Ytterdörren öppnas efter 21.00 och hallen får svagt ljus.", "Balkongdörren står öppen när regnet börjar och mobilen får en notis.", "Kylskåpsdörren har varit öppen i två minuter och köksskärmen visar en påminnelse."], [["Var de gör mest nytta", "Ytterdörr, balkongdörr, förråd och kylskåp är bättre startpunkter än varje innerdörr i huset."], ["Välj Zigbee om du kan", "Batterisensorer mår ofta bra av Zigbee eftersom de drar lite ström och slipper belasta hemmets wifi."], ["Tänk igenom notiser", "Skicka inte notis varje gång dörren öppnas. Skicka bara när något är ovanligt: fel tid, för länge öppet eller ingen är hemma."], ["Bra första automation", "När ytterdörren öppnas på morgonen kan hallen tändas och dashboarden visa dagens viktigaste tre saker."]]),
article("temperatur-fuktsensor-barnrum", "Temperatur- och fuktsensor i barnrum: när är det värt det?", "Så använder du klimatdata utan att göra barnrummet till ett teknikprojekt.", "guide", ["temperature-sensor", "smart-thermostat"], ["guide","klimat","barnrum","sensorer"], "Temperatur och fukt är lätt att mäta men svårt att använda vettigt. Nyttan kommer när mätningen leder till en enkel åtgärd: vädra, dra ner värmen, flytta ett element eller upptäcka att ett rum alltid blir kallt på natten.", ["Barnrummet sjunker under 18 grader efter midnatt och dashboarden visar det nästa morgon.", "Fukten stiger i badrummet och en påminnelse säger att dörren bör stå öppen.", "Sovrummet blir för varmt efter läggning och termostaten sänker lite tidigare."], [["Börja med historik", "Titta på en vecka innan du automatiserar. Ofta ser du snabbt om problemet är kvällsvärme, nattkyla eller dålig ventilation."], ["Notiser ska vara sällsynta", "Ingen behöver få ping för varje temperaturändring. Larma bara när värdena är ovanliga eller håller i sig länge."], ["Barnrum kräver stabilitet", "Om sensorn används för nattvärme ska den vara pålitlig och ha bra batteriindikator."], ["När termostat behövs", "Om samma rum ofta är för kallt eller varmt kan smart elementstyrning vara mer relevant än ännu fler lampor."]]),
article("home-assistant-forsta-10-automationer", "De första 10 automationerna i Home Assistant för familjer", "Tio enkla automationer som passar innan hemmet blir för avancerat.", "guide", ["smart-button", "smart-bulb", "motion-sensor", "door-window-sensor"], ["guide","home-assistant","rutiner","knappar"], "De första automationerna ska vara tråkigt praktiska. De ska fungera för alla i familjen och helst gå att förstå utan att någon öppnar Home Assistant.", ["Hallampa tänds svagt när någon går upp på natten.", "Godnatt-knappen släcker kök och hall men lämnar nattljus.", "Dörrsensor påminner om balkongdörren står öppen när alla går hemifrån."], [["1–3: ljus som hjälper", "Nattljus i hall, kvällsläge i barnrum och morgonljus i kök är tre automationer som märks snabbt."], ["4–6: fysiska knappar", "God natt, hemifrån och lägg till inköp är bra knappfunktioner eftersom de startas där beteendet redan sker."], ["7–8: sensorer utan brus", "Rörelsesensor för badrum nattetid och dörrsensor för ytterdörren ger nytta utan att skapa många notiser."], ["9–10: dashboard", "Visa dagens schema och en enkel statusrad: hemma, borta, nattläge eller morgonläge."]]),
article("smart-hem-semesterlage-familj", "Semesterläge i smart hem: lampor, vatten och trygghet", "En praktisk checklista för hemmet när familjen är bortrest.", "guide", ["smart-bulb", "water-leak-sensor", "door-window-sensor"], ["guide","säkerhet","vattenlackage","belysning"], "Semesterläge behöver inte vara avancerat. Det viktigaste är att minska risken för vattenskador, se om något öppnas oväntat och låta några lampor bete sig normalt utan att överdriva.", ["Vattenlarm under diskmaskinen är aktivt även när alla är borta.", "En lampa tänds kort på kvällen, men inte exakt samma minut varje dag.", "Ytterdörren öppnas när ingen ska vara hemma och du får en tydlig notis."], [["Börja med vatten", "Vattenläckage är ofta mer ekonomiskt relevant än om vardagsrumslampan tänds."], ["Dörrar och fönster", "En sensor på ytterdörr eller balkongdörr räcker långt. Undvik att övervaka allt om det bara ger oro."], ["Lampor ska vara rimliga", "Simulera inte ett disco. En eller två lampor vid normala tider ser mer naturligt ut."], ["Testa innan resan", "Kör semesterläget en kväll hemma så du ser att inget konstigt händer."]]),
article("basta-smarta-knappar-home-assistant", "Bästa smarta knapparna för Home Assistant", "Vad du ska välja när knappen ska fungera i hall, kök, barnrum och sovrum.", "köpguide", ["smart-button", "zigbee-hub"], ["kopguide","home-assistant","knappar","zigbee"], "Smarta knappar är ofta bättre än röststyrning. De är fysiska, snabba och går att använda av barn, gäster och trötta vuxna.", ["Knappen vid ytterdörren kör hemifrån-läge.", "Knappen vid sängen släcker huset utan att mobilen tas fram.", "Knappen vid kylen lägger till standardvaror på inköpslistan."], [["Välj efter placering", "En liten knapp passar vid sängen. En tydligare knapp passar i hallen där flera personer ska hitta den snabbt."], ["Zigbee är oftast bäst", "För batteriknappar är Zigbee vanligtvis stabilt och energisnålt, särskilt med en bra hubb."], ["Dubbeltryck kan bli rörigt", "Börja med enkeltryck. Lägg till dubbeltryck först när familjen använder knappen regelbundet."], ["Köp inte för många", "Två bra placerade knappar gör mer nytta än tio som ingen minns."]]),
article("smart-hem-for-lagenhet", "Smart hem i lägenhet: utan borrning och utan strul", "Hyresvänliga lösningar för lampor, sensorer, knappar och dashboard.", "guide", ["smart-button", "smart-bulb", "door-window-sensor", "tablet-wall"], ["guide","hyresratt","budget","knappar"], "I lägenhet är det smart att välja lösningar som går att flytta, återställa och montera utan märken. Det gör också projektet billigare och lättare att ändra.", ["En knapp med dubbelhäftande tejp sitter vid dörren.", "En gammal surfplatta står på köksbänken i stället för att skruvas upp.", "En dörrsensor på balkongen varnar om den står öppen när det börjar regna."], [["Belysning först", "Smarta lampor kräver ingen installation och kan följa med vid flytt."], ["Sensorer med tejp", "Dörrsensorer och rörelsesensorer kan monteras försiktigt och tas ner utan större spår."], ["Undvik fasta ingrepp", "Väggbrytare, elinstallation och inbyggnad är sällan rätt start i hyresrätt."], ["Gör det flyttbart", "Om lösningen kan packas ner på en kväll är den oftast rätt nivå."]]),
article("smart-hem-for-vintermorgon", "Smart hem för mörka vintermorgnar", "Ljus, värme och enkla påminnelser när morgonen är som segast.", "guide", ["smart-bulb", "smart-thermostat", "tablet-wall"], ["guide","morgon","belysning","klimat"], "Vintermorgnar gör allt lite trögare. Rätt ljus och tydliga signaler kan hjälpa utan att hemmet behöver låta som en väckarklocka.", ["Köket får mjukt ljus innan barnen kommer upp.", "Hallens ljus blir klarare när det är dags för ytterkläder.", "Dashboarden visar om det behövs mössa, regnkläder eller gympapåse."], [["Ljus före ljud", "Många familjer mår bättre av långsam ljusstart än av fler alarm."], ["Visa väder praktiskt", "Skriv inte bara temperatur. Visa vad det betyder: regnjacka, vantar eller cykelhjälm."], ["Värme i rätt rum", "Om ett barnrum är kallt på morgonen kan termostatstyrning i just det rummet vara mer värdefull än nya lampor."], ["Håll rutinen kort", "Morgonvyn ska visa färre saker än du tror. Annars slutar alla titta."]]),
article("basta-sensorer-home-assistant-nyborjare", "Bästa sensorerna för Home Assistant-nybörjare", "Vilka sensorer är värda pengarna först: rörelse, dörr, vatten, temperatur eller närvaro?", "köpguide", ["motion-sensor", "door-window-sensor", "water-leak-sensor", "temperature-sensor"], ["kopguide","home-assistant","sensorer","zigbee"], "Sensorer är lätta att köpa för många av. Den bättre frågan är vilken sensor som löser ett konkret problem hemma redan första veckan.", ["Rörelsesensor gör nattljus i hallen.", "Vattenläckagesensor ligger under diskmaskinen.", "Dörrsensor visar om balkongdörren står öppen."], [["Rörelsesensor", "Bäst för nattljus och enkla rum där någon passerar kort."], ["Dörrsensor", "Bäst för ytterdörr, balkong, förråd och kylskåp."], ["Vattenläckagesensor", "Inte roligast men ofta mest rationell. Placera vid maskiner och rör."], ["Temperatursensor", "Bra när ett rum faktiskt är för kallt, varmt eller fuktigt och du vill följa mönster."]]),
article("home-assistant-dashboard-barn", "Dashboard för barn: veckovy utan informationskaos", "Så gör du en barnvänlig vy med färre ord och tydligare signaler.", "guide", ["tablet-wall", "smart-button"], ["guide","dashboard","barnrum","kalender"], "En dashboard för barn ska inte vara en vuxenkalender i mindre text. Den ska visa dagen med enkla ord, färger och nästa steg.", ["Barnet ser skola, träning och läggdags utan att fråga tre gånger.", "En färg visar om morgonen är lugn eller bråttom.", "Knappen 'klar' ger en tydlig avslutssignal."], [["Visa idag först", "Barn behöver inte alltid se hela månaden. Idag och imorgon räcker ofta."], ["Använd färger konsekvent", "Samma färg för skola, aktivitet och vila gör vyn lättare att förstå."], ["Färre widgets", "Väder, kalender, inköp och rutiner på samma skärm kan bli för mycket. Välj det som hjälper barnet."], ["Placera lågt nog", "Om barnen ska använda skärmen måste de kunna se den utan att stå på tå."]]),
article("smart-hem-utan-moln", "Smart hem utan moln: vad fungerar lokalt?", "Varför lokala lösningar kan vara bättre för familjens viktigaste rutiner.", "guide", ["zigbee-hub", "smart-button", "smart-bulb"], ["guide","home-assistant","zigbee","säkerhet"], "När internet ligger nere ska läggningsljus, hallknappar och nattljus helst fortfarande fungera. Därför är lokala smart hem-lösningar värda att förstå.", ["Godnatt-knappen fungerar även om en molntjänst har problem.", "Nattljuset i hallen styrs lokalt mellan sensor och lampa.", "Dashboarden kan fortfarande visa lokala sensorer."], [["Vad lokalt betyder", "Lokalt betyder att styrningen sker hemma, inte bara via en extern molntjänst."], ["Zigbee och Home Assistant", "Många Zigbee-prylar kan styras lokalt via Home Assistant eller en hubb som stödjer lokal kontroll."], ["Vad som ändå kan kräva internet", "Väder, vissa röstassistenter och externa kalenderkällor kan fortfarande behöva internet."], ["Prioritera viktiga rutiner", "Läggning, nattljus och hemifrån-knapp är bättre kandidater för lokal styrning än dekorationsljus."]]),
article("basta-smarta-termostater-familj", "Bästa smarta termostaterna för familjer", "När smart värmestyrning är värd pengarna och när en vanlig termostat räcker.", "köpguide", ["smart-thermostat", "temperature-sensor"], ["kopguide","klimat","värme","barnrum"], "Smart värmestyrning kan ge jämnare sovrum och lägre energislöseri, men bara om problemet faktiskt handlar om temperatur och inte drag, dålig isolering eller fel placering.", ["Barnrummet blir kallt efter midnatt och värmen höjs tidigare.", "Hemmakontoret värms bara på vardagsmorgnar.", "Temperatursensor visar att problemet egentligen är vädring, inte elementet."], [["Börja med mätning", "Mät temperaturen en vecka innan du köper styrning. Annars är risken stor att du löser fel problem."], ["Rum för rum", "Styr ett problemrum först. Hela hemmet behöver inte smart termostat direkt."], ["Barnrum och sömn", "Jämn temperatur kan vara mer värdefull än en exakt temperatur."], ["Kontrollera kompatibilitet", "Element, radiatorventiler och värmesystem skiljer sig mycket. Köp inte innan du vet vad som passar."]]),
article("smarta-hem-rutiner-for-tonaringar", "Smarta hem-rutiner för tonåringar utan tjat", "Lösningar för nycklar, tider, laddare och kvällsrutiner som inte känns barnsliga.", "guide", ["smart-button", "door-window-sensor", "smart-plug"], ["guide","rutiner","notiser","knappar"], "Tonåringar behöver ofta mindre synliga system än små barn. Det ska kännas som praktiska genvägar, inte som övervakning.", ["En diskret knapp vid skrivbordet startar fokusläge.", "Smart plug stänger skärmladdare vid bestämd tid om familjen kommit överens om det.", "Dörrsensor på ytterdörren kan ge en tyst status utan att någon behöver ringa."], [["Prata om syftet", "Teknik som upplevs som kontroll kommer inte användas. Börja med problem tonåringen själv vill slippa."], ["Fokusläge", "En knapp kan tända skrivbordslampa, sänka störande lampor och starta en timer."], ["Laddning och prylar", "Smart plug kan hjälpa om laddare glöms på, men ska inte bli en ständig konfliktpunkt."], ["Välj tysta signaler", "Diskreta lampor och dashboardstatus fungerar ofta bättre än högljudda notiser."]]),
article("smarta-hem-gaster-och-barnvakt", "Smart hem när barnvakt eller gäster är hemma", "Gör hemmet begripligt även för den som inte har appen.", "guide", ["smart-button", "smart-bulb", "tablet-wall"], ["guide","knappar","dashboard","belysning"], "Ett smart hem är inte färdigt förrän en barnvakt kan tända, släcka och förstå kvällen utan att ringa dig.", ["En fysisk knapp märkt 'god natt' gör rätt saker i rätt ordning.", "Köksskärmen visar wifi, läggtid och nödnummer.", "Lampor har vanliga brytare eller tydliga knappar som fungerar."], [["Appar hjälper inte gäster", "Utgå från att gästen inte har app, konto eller tid att lära sig systemet."], ["Tre knappar räcker", "Tänd hall, kvällsläge och god natt är bättre än avancerade scener."], ["Dashboard med basinfo", "Visa bara det en barnvakt faktiskt behöver: tider, kontakt, mat, läggning."], ["Behåll manuell kontroll", "Om en vanlig strömbrytare slutar fungera normalt blir hemmet svårare, inte smartare."]]),
article("basta-narvarosensorer-familj", "Bästa närvarosensorer för familjehem", "När närvarosensor är bättre än rörelsesensor och var den passar sämre.", "köpguide", ["motion-sensor", "zigbee-hub"], ["kopguide","sensorer","zigbee","belysning"], "Närvarosensorer kan känna att någon är kvar i rummet, inte bara att någon rörde sig nyss. Det gör dem intressanta för kök, kontor och vardagsrum, men de är inte alltid rätt i hallen.", ["Kökslampan slocknar inte när någon sitter stilla vid läxorna.", "Kontorsljuset stannar på under videosamtal.", "Hallen använder vanlig rörelsesensor eftersom passager är korta."], [["Närvaro vs rörelse", "Rörelsesensor ser rörelse. Närvarosensor försöker se att någon fortfarande är där."], ["Bra rum", "Kök, kontor, vardagsrum och hobbyrum är bra kandidater."], ["Sämre rum", "Hall, förråd och trappor behöver ofta bara vanlig rörelse."], ["Tänk placering", "Fel placering kan ge konstiga resultat. Testa tillfälligt innan du monterar permanent."]]),
article("smart-hem-energispara-familj", "Spara energi med smart hem utan att familjen blir irriterad", "Praktiska energitips som inte gör hemmet obekvämt.", "guide", ["smart-plug", "temperature-sensor", "smart-thermostat"], ["guide","energi","klimat","pluggar"], "Energisparande fungerar bäst när det inte märks som försämrad vardag. Smarta hem kan hjälpa genom att visa mönster och stänga av sådant som faktiskt glöms.", ["Golvlampan stängs av automatiskt efter läggdags.", "Temperaturhistorik visar att ett rum övervärms på eftermiddagen.", "Energimätande pluggar avslöjar vilka apparater som faktiskt drar ström."], [["Mät innan du styr", "Gissa inte. En smart plug med energimätning kan visa vad som är värt att bry sig om."], ["Stäng av glömt", "Lampor, vissa laddare och dekorationsljus är enkla första steg."], ["Var försiktig med komfort", "Sänk inte värmen så att familjen börjar överstyra systemet. Då försvinner nyttan."], ["Små vinster räknas", "Målet är inte att optimera allt, utan att ta bort onödigt spill som sker varje dag."]]),
article("smarta-hem-checklista-nytt-hem", "Checklista: smart hem när du flyttar till nytt hem", "Vad du ska installera först och vad som kan vänta.", "guide", ["water-leak-sensor", "smart-button", "smart-bulb", "door-window-sensor"], ["guide","checklista","budget","sensorer"], "När man flyttar är det lätt att köpa allt samtidigt. Men ett nytt hem behöver först förstås: var blir det mörkt, var glöms saker och var finns risk för vatten?", ["Vattenlarm placeras innan första långa resan.", "En knapp vid nya ytterdörren blir hemifrån-rutin.", "Barnrummens lampor får kvällsläge innan fler sensorer köps."], [["Första veckan", "Sätt vattenlarm vid maskiner och lös de viktigaste lamporna."], ["Första månaden", "Titta på hur familjen faktiskt rör sig: hall, kök, badrum och sovrum."], ["Vänta med avancerat", "Bygg inte stora automationer innan du vet vilka problem hemmet har."], ["Dokumentera enkelt", "Skriv var sensorer sitter och vilket batteri de har. Det sparar tid senare."]]),
article("basta-vattenlarm-diskmaskin", "Bästa vattenlarm under diskmaskin", "Vad du ska tänka på när sensorn ska ligga där läckan ofta börjar.", "köpguide", ["water-leak-sensor"], ["kopguide","vattenlackage","sensorer","kok"], "Diskmaskinen är en av de mest logiska platserna för vattenlarm. Sensorn är billig jämfört med följden av ett läckage som upptäcks sent.", ["Sensorn ligger under framkanten där vatten först rinner ut.", "Larmet skickas till vuxnas telefoner och visas på köksskärmen.", "Batteristatus kontrolleras automatiskt en gång i månaden."], [["Placering", "Sensorn ska ligga där vatten faktiskt hamnar, inte längst bak där du aldrig kommer åt den."], ["Ljud eller smart larm", "Ett lokalt pip kan räcka om någon är hemma. Smart notis är bättre när hemmet är tomt."], ["Batteri", "Välj en sensor där batteristatus går att se. Ett dött vattenlarm är bara plast."], ["Testa med lite vatten", "Testa sensorn kontrollerat efter installation så du vet att larmet går fram."]]),
article("ikea-tradfri-home-assistant-familj", "IKEA Trådfri och Home Assistant i familjehem", "När IKEA-prylar räcker och när du bör välja något annat.", "guide", ["smart-bulb", "smart-button", "zigbee-hub"], ["guide","home-assistant","zigbee","belysning"], "IKEA Trådfri är attraktivt för familjer eftersom det finns lokalt, är relativt billigt och har många enkla lampor och knappar. Men allt passar inte alla system perfekt.", ["Barnrummets lampa får kvällsläge med en enkel fjärr.", "Köket använder IKEA-lampa men styrs från Home Assistant.", "En billig knapp testas innan familjen köper fler."], [["Bra för belysning", "Lampor och enkla styrningar är ofta starka IKEA-köp."], ["Kolla kompatibilitet", "Om du använder Home Assistant med egen Zigbee-lösning ska du dubbelkolla stöd för modellen."], ["Pris och tillgänglighet", "Fördelen är att du kan köpa en pryl snabbt och lämna tillbaka enklare än många nätköp."], ["När annat är bättre", "För avancerade sensorer, närvaro eller särskilda formfaktorer kan Aqara, Hue eller andra märken passa bättre."]]),
article("aqara-sensorer-home-assistant", "Aqara-sensorer i Home Assistant: vad passar familjer?", "Dörr, temperatur, vatten och rörelse – vilka Aqara-sensorer är mest användbara?", "köpguide", ["door-window-sensor", "temperature-sensor", "water-leak-sensor", "motion-sensor"], ["kopguide","home-assistant","zigbee","sensorer"], "Aqara är populärt eftersom sensorerna ofta är små, relativt billiga och Zigbee-baserade. För familjer är frågan vilka som gör verklig nytta, inte vilka som är roligast att köpa.", ["Dörrsensor på balkongdörren ger regnvarning.", "Vattensensor under handfatet upptäcker dropp.", "Temperatursensor visar varför ett barnrum känns kallt."], [["Dörrsensor", "En av de mest flexibla sensorerna: dörr, fönster, låda, kyl eller förråd."], ["Vattensensor", "Bra där skador kan bli dyra och där du sällan tittar."], ["Temperatur och fukt", "Användbar när du följer mönster över tid, inte bara tittar på siffran."], ["Rörelse", "Bra för hall och nattljus, men inte för rum där människor sitter stilla länge."]]),
article("philips-hue-vs-billiga-zigbee-lampor", "Philips Hue eller billiga Zigbee-lampor?", "Hur du väljer belysning när barnrum, hall och kök ska fungera varje dag.", "köpguide", ["smart-bulb", "zigbee-hub"], ["kopguide","zigbee","belysning","barnrum"], "Hue är stabilt och lätt att förstå, men kostar mer. Billiga Zigbee-lampor kan vara fullt tillräckliga om du accepterar lite mer kontrollarbete.", ["Barnrummet får Hue om stabilitet är viktigast.", "Förråd och enklare lampor får billigare Zigbee-alternativ.", "Köket prioriterar bra vitt ljus framför färgeffekter."], [["När Hue är värt priset", "Om lampan används varje kväll och alla i familjen måste kunna lita på den är stabilitet värd pengar."], ["När billigt räcker", "Dekorationsljus, förråd och testprojekt kan ofta använda billigare alternativ."], ["Tänk på färgkvalitet", "För kök och läsning är bra vitt ljus viktigare än många färger."], ["Blanda lagom", "Det går att blanda märken, men dokumentera vad som sitter var."]]),
article("robotdammsugare-med-husdjur-och-barn", "Robotdammsugare med husdjur och barn", "Vad som spelar roll när hemmet har smulor, hår, leksaker och hinder.", "köpguide", ["robot-vacuum"], ["kopguide","städning","hund","barnrum"], "Barn och husdjur gör robotdammsugare mer relevant, men också mer krävande. Hinder, hår och småsaker avgör mer än snygga appfunktioner.", ["Köket körs efter middag när stolarna är upplyfta.", "Hallen får extra schema under grusperioden.", "Robotens körning pausas om leksaker ligger kvar på golvet."], [["Hinderigenkänning", "Om golven ofta har sladdar, strumpor eller leksaker är hinderhantering viktig."], ["Hår och borstar", "Husdjurshår kräver enklare rengöring av borstar och filter."], ["Schema per rum", "Barnfamiljer har ofta mer nytta av korta körningar i kök och hall än av hela huset varje gång."], ["Ljudnivå", "En robot som stör läggning eller läxa kommer inte köras när den borde."]]),
article("smart-hem-for-sommarstuga", "Smart hem i sommarstuga: vatten, värme och fjärrkoll", "En enkel setup för stuga där du inte är varje dag.", "guide", ["water-leak-sensor", "temperature-sensor", "smart-thermostat", "door-window-sensor"], ["guide","säkerhet","klimat","vattenlackage"], "I en sommarstuga är smart hem mindre en bekvämlighetsgrej och mer ett sätt att se om något gått fel: vatten, kyla, fukt eller en dörr som står öppen.", ["Temperaturen sjunker under gränsen och du får varning.", "Vattenlarm vid varmvattenberedaren skickar notis.", "Dörrsensor visar om förrådet öppnats oväntat."], [["Vatten och frost först", "Riskerna är ofta större än behovet av smart belysning."], ["Internet är svag punkt", "Om stugan har instabil uppkoppling behöver du tänka på vad som fungerar lokalt och vad som kräver moln."], ["Få notiser", "Skicka bara viktiga larm. Annars börjar man ignorera stugan."], ["Batterier", "Planera batteribyten efter säsong, inte när sensorn redan dött."]]),
article("smarta-hem-under-50-euro", "Smart hem under 50 euro: vad ger mest nytta?", "Tre små köp som kan göra märkbar skillnad hemma.", "köpguide", ["smart-button", "smart-bulb", "motion-sensor", "water-leak-sensor"], ["kopguide","budget","knappar","sensorer"], "Med liten budget gäller det att välja prylar som löser ett tydligt problem direkt. En knapp, en lampa och en sensor kan räcka långt.", ["En knapp vid dörren släcker lampor.", "En smart lampa gör kvällsläge i barnrum.", "En vattensensor skyddar diskmaskinen."], [["Bästa första köp", "En smart knapp är ofta mest användbar per euro eftersom den gör rutiner fysiska."], ["Belysning som märks", "En lampa i barnrum eller hall ger mer nytta än dekorationsljus."], ["Sensor med tydligt jobb", "Välj rörelse för nattljus eller vatten för läckagerisk. Köp inte sensor utan plan."], ["Vänta med hubb om budgeten är tajt", "Om du redan har ett system kan Zigbee vara bäst. Annars kan ett enklare första köp vara rimligare."]]),
article("smarta-hem-under-200-euro", "Smart hem under 200 euro: ett rimligt startpaket", "En balanserad inköpslista för familj som vill börja ordentligt men inte överköpa.", "köpguide", ["zigbee-hub", "smart-button", "smart-bulb", "water-leak-sensor", "motion-sensor"], ["kopguide","budget","zigbee","sensorer"], "Med 200 euro kan du bygga en stabil grund: hubb, några lampor, knappar och sensorer som löser riktiga vardagsproblem.", ["Hallen får rörelsestyrt nattljus.", "Barnrummet får kvällsläge.", "Diskmaskinen får vattenlarm.", "Ytterdörren får hemifrån-knapp."], [["Prioritera stabil grund", "En hubb kan vara värd pengarna om du vill använda flera Zigbee-sensorer och knappar."], ["Köp få av varje", "En knapp, en rörelsesensor, en vattensensor och två lampor säger mer än tio lampor på en gång."], ["Placera innan du expanderar", "Testa var saker faktiskt används innan du beställer fler."], ["Spara till robot senare", "Robotdammsugare kan vara bra, men äter hela budgeten om du köper den först."]]),
article("vanliga-fel-home-assistant-familjer", "Vanliga Home Assistant-fel i barnfamiljer", "Misstag som gör systemet svårare än vardagen det skulle hjälpa.", "guide", ["smart-button", "tablet-wall"], ["guide","home-assistant","rutiner"], "Home Assistant kan bli väldigt bra i ett familjehem, men det kan också bli ett hobbyprojekt som ingen annan förstår. De vanligaste felen handlar om för mycket logik och för lite vardag.", ["En automation släcker lampan medan någon fortfarande läser.", "Dashboarden visar 40 saker men ingen hittar dagens hämtning.", "Allt kräver mobilen och barnvakten kan inte tända hallen."], [["För många automationer", "Om ingen minns vad som händer när är systemet för komplext."], ["För lite manuell kontroll", "Det måste alltid gå att tända, släcka och stoppa något enkelt."], ["Dashboard som kontrollpanel", "En familjedashboard ska visa vardag, inte vara serverrum."], ["Notisbrus", "Varje notis ska ha ett tydligt beslut kopplat till sig. Annars är den bara störning."]]),
article("smart-hem-for-regniga-dagar", "Smart hem för regniga dagar: hall, tvätt och tork", "Små lösningar när ytterkläder, skor och tvätt tar över hemmet.", "guide", ["door-window-sensor", "temperature-sensor", "smart-plug"], ["guide","hall","klimat","rutiner"], "Regniga dagar skapar andra problem än vanliga dagar: blöta skor, mer tvätt, mörkare hall och saker som behöver torka innan nästa morgon.", ["Dashboarden visar regnjacka innan familjen går.", "En fuktsensor påminner om vädring i tvättstugan.", "Hallampan tänds tidigare när det är mörkt ute."], [["Visa rätt kläder", "Väder ska översättas till handling: stövlar, regnjacka eller extra vantar."], ["Torkplats", "En smart plug kan styra en godkänd avfuktare eller fläkt enligt tydliga säkerhetsregler."], ["Hallen behöver ljus", "Mörka dagar kan hallen tändas tidigare så skor och väskor faktiskt syns."], ["Undvik överstyrning", "Regnläge ska hjälpa, inte ändra hela hemmet."]]),
article("smart-hem-nar-internet-gar-ner", "När internet går ner: vad fungerar i smarta hemmet?", "Så bygger du rutiner som inte faller ihop när uppkopplingen strular.", "guide", ["zigbee-hub", "smart-button", "smart-bulb"], ["guide","home-assistant","zigbee","säkerhet"], "Internetproblem är ett bra test av smarta hemmet. Om allt viktigt slutar fungera är systemet för beroende av molnet.", ["Hallknappen tänder fortfarande lampan.", "Godnatt-läget fungerar lokalt.", "Väderwidgeten är borta men kalender och lokala sensorer syns."], [["Dela upp viktigt och oviktigt", "Nattljus och knappar är viktiga. Dekorationsscener kan vänta på internet."], ["Lokala protokoll", "Zigbee och lokal Home Assistant-styrning kan minska beroendet av molntjänster."], ["Testa medvetet", "Stäng av internet en kort stund och se vad som faktiskt händer."], ["Ha en reserv", "Vanliga brytare och manuella rutiner behövs fortfarande."]]),
article("kopguide-home-assistant-green", "Köpguide: Home Assistant Green för familjer", "När Home Assistant Green är rätt start och när du ska välja annat.", "köpguide", ["zigbee-hub", "tablet-wall"], ["kopguide","home-assistant","dashboard"], "Home Assistant Green är intressant för familjer eftersom det gör starten enklare än att bygga allt själv. Men det är fortfarande ett system som kräver eftertanke.", ["Familjen får lokal styrning utan att en laptop står igång.", "Dashboarden i köket hämtar data från samma system.", "Zigbee kräver fortfarande rätt adapter eller hubblösning."], [["Vem den passar", "Den passar dig som vill ha Home Assistant utan att börja med Raspberry Pi-installation och felsökning."], ["Vad som tillkommer", "Du behöver fortfarande tänka på Zigbee, backup och vilka prylar som ska anslutas."], ["Familjens krav", "Systemet ska vara stabilt nog att andra vågar använda knappar och lampor."], ["Alternativ", "Raspberry Pi, begagnad mini-PC eller färdiga hubbar kan vara bättre beroende på budget och intresse."]]),
article("faq-smart-hem-barnfamilj", "FAQ: smart hem för barnfamiljer", "Svar på vanliga frågor innan du börjar köpa prylar.", "guide", ["smart-button", "smart-bulb", "water-leak-sensor"], ["guide","faq","budget","home-assistant"], "Innan man börjar köpa smarta prylar dyker samma frågor upp: vad behövs, vad kostar det, vad är säkert och hur undviker man appkaos?", ["Familjen börjar med en knapp, en lampa och ett vattenlarm.", "Home Assistant väntar tills första rutinen faktiskt används.", "Barnvakten kan fortfarande tända lampor utan app."], [["Måste man ha Home Assistant?", "Nej. Du kan börja med enklare system. Home Assistant blir mest intressant när flera märken och rutiner ska fungera tillsammans."], ["Vad ska man köpa först?", "En smart knapp, en användbar lampa och en sensor med tydligt jobb är en bra start."], ["Är det säkert?", "Smarta hem kräver uppdateringar, starka konton och rimliga val. Undvik att koppla allt kritiskt till okända molntjänster."], ["Hur undviker man att det blir dyrt?", "Köp för ett problem i taget. Om lösningen inte används, köp inte nästa pryl än."]]),
]

added = 0
for a in new_articles:
    if a["slug"] not in existing:
        articles.append(a)
        existing.add(a["slug"])
        added += 1

articles_path.write_text(json.dumps(articles, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
products_path.write_text(json.dumps(products, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
links_path.write_text(json.dumps(links, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"added_articles={added}")
print(f"total_articles={len(articles)}")
print(f"products={len(products)}")
