#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
articles_path = ROOT / "content" / "articles" / "articles.json"
products_path = ROOT / "data" / "products.json"
links_path = ROOT / "data" / "affiliate_links.json"
articles = json.loads(articles_path.read_text(encoding="utf-8"))
products = json.loads(products_path.read_text(encoding="utf-8"))
links = json.loads(links_path.read_text(encoding="utf-8"))
existing = {a["slug"] for a in articles}
product_ids = {p["id"] for p in products}

for p in [
    {"id":"air-quality-sensor","name":"Luftkvalitets- eller CO2-sensor","category":"klimat","price_hint":"40–180 €","best_for":"sovrum, hemmakontor och klassisk vädra-påminnelse","note":"Köp bara om värdet leder till handling. CO2 är mest användbart där flera personer vistas länge."},
    {"id":"smart-smoke-detector","name":"Smart brandvarnare / rökdetektor","category":"säkerhet","price_hint":"25–100 €","best_for":"varningar när du inte är i samma rum","note":"Ersätter inte kravet på godkända brandvarnare. Se smart funktion som extra lager, inte enda skydd."},
    {"id":"smart-lock","name":"Smart lås","category":"lås","price_hint":"120–300 €","best_for":"tillfälliga koder, barnvakt och koll på låst dörr","note":"Bör väljas försiktigt. Mekanisk kvalitet och reservväg är viktigare än appfunktioner."},
    {"id":"smart-blinds","name":"Smarta gardiner eller rullgardinsmotor","category":"belysning","price_hint":"50–250 €","best_for":"morgonljus, värme och mörkläggning","note":"Bra i ett eller två rum. Dyrt och onödigt att börja med överallt."},
]:
    if p["id"] not in product_ids:
        products.append(p); product_ids.add(p["id"])

links.setdefault("air-quality-sensor", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=co2+sensor+luftkvalitet+smart+hem&tag=smartahemmet-21","label":"Se luftkvalitets- och CO2-sensorer på Amazon","target_pages":[]})
links.setdefault("smart-smoke-detector", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=smart+brandvarnare+r%C3%B6kdetektor&tag=smartahemmet-21","label":"Se smarta brandvarnare på Amazon","target_pages":[]})
links.setdefault("smart-lock", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=smart+l%C3%A5s+d%C3%B6rr&tag=smartahemmet-21","label":"Se smarta lås på Amazon","target_pages":[]})
links.setdefault("smart-blinds", {"status":"active","network":"Amazon Associates","url":"https://www.amazon.se/s?k=smarta+gardiner+rullgardinsmotor&tag=smartahemmet-21","label":"Se smarta gardiner på Amazon","target_pages":[]})

def a(slug,title,description,category,prods,tags,intro,examples,sections):
    return {"slug":slug,"title":title,"description":description,"category":category,"products":prods,"tags":tags,"intro":intro,"examples":examples,"sections":sections+[
        ["När det är värt att bygga vidare", "Bygg vidare först när den enkla versionen används flera gånger i veckan. Om familjen går runt lösningen är nästa steg inte fler prylar utan bättre placering, enklare signal eller mindre automation."],
        ["Det som ofta avgör", "Placering, batteribyten och tydlig manuell kontroll avgör mer än avancerade appfunktioner. En lösning som andra i hemmet förstår vinner över en snygg men skör automation."]
    ]}

new_articles=[
a("basta-luftkvalitetssensorer-barnrum","Bästa luftkvalitetssensorer för barnrum och sovrum","CO2, temperatur och fukt – när luftdata faktiskt hjälper hemma.","köpguide",["air-quality-sensor","temperature-sensor"],["kopguide","luftkvalitet","co2","klimat","barnrum"],"Luftkvalitet låter avancerat, men i praktiken handlar det ofta om en enkel fråga: behöver vi vädra? I sovrum, barnrum och hemmakontor kan CO2 och fukt ge tydliga mönster som annars bara känns som trötthet eller dålig luft.",["CO2 stiger i barnrummet efter läggning och dashboarden visar vädra-symbol på morgonen.","Fukt i badrummet ligger kvar för länge och familjen öppnar dörren tidigare.","Hemmakontoret får en diskret signal efter två timmars möte."],[["CO2 är mest konkret", "CO2-värde är ofta lättare att agera på än vaga luftkvalitetsindex. Högt värde betyder oftast: vädra."],["Fukt är praktiskt", "Fukt hjälper i badrum, tvättstuga och kalla rum där mögelrisk eller instängd lukt kan bli problem."],["Undvik notisbrus", "Visa värdet på dashboard eller ge en enda tydlig signal. Ingen behöver löpande luftnotiser hela dagen."],["Köpguide", "Prioritera tydlig display, Home Assistant-stöd om du använder det och rimlig kalibrering."]]),
a("co2-sensor-home-assistant","CO2-sensor i Home Assistant: så använder du den vettigt","Från siffra till handling: vädra, dashboard och diskreta signaler.","guide",["air-quality-sensor","tablet-wall"],["guide","co2","home-assistant","dashboard","klimat"],"En CO2-sensor blir användbar först när värdet kopplas till något familjen förstår. Siffran i sig säger lite för barn, gäster och trötta vuxna. En tydlig färg eller vädra-symbol fungerar bättre.",["Köksskärmen visar gul symbol när luften i vardagsrummet blir tung.","Efter läggning loggas sovrummets CO2 så ni ser om dörren behöver stå på glänt.","Hemmakontoret får en liten lampa som byter färg före huvudvärken kommer."],[["Visa zoner", "Visa inte alla mätvärden överallt. Sovrum, vardagsrum och kontor räcker för de flesta."],["Automatisera försiktigt", "Om du har ventilation kan CO2 styra den, men börja med påminnelse innan du gör automatisk styrning."],["Färg före siffror", "Grön, gul och röd signal är lättare att förstå än ppm-tal."],["Historik är viktig", "Titta på mönster över flera kvällar innan du drar slutsatser."]]),
a("smart-brandvarnare-familj","Smart brandvarnare i familjehem: extra trygghet, inte ersättning","Vad smarta rökdetektorer kan göra och vad de inte ska ersätta.","guide",["smart-smoke-detector"],["guide","brand","säkerhet"],"Brandvarnare är inte platsen för tekniklek. Smarta funktioner kan vara bra som extra lager, särskilt notiser när du inte är hemma, men de ersätter inte godkända och korrekt placerade vanliga brandvarnare.",["Larmet i hallen hörs lokalt och skickar dessutom notis.","Batteristatus syns innan pipandet börjar mitt i natten.","Familjen testar brandvarnare samma datum varje månad."],[["Börja med grundskydd", "Se först till att hemmet har godkända brandvarnare på rätt platser."],["Smart funktion som extra lager", "Notiser, batteristatus och koppling till lampor kan vara hjälpsamt, men får inte vara enda skyddet."],["Tänk på natt", "Om larm går nattetid kan lampor tändas svagt för väg ut, men det ska testas ordentligt."],["Underhåll", "Planera test och batteribyte. En smart brandvarnare utan underhåll är inte smart."]]),
a("basta-smarta-las-barnfamilj","Bästa smarta lås för barnfamiljer: när är det värt det?","Kod, nycklar, barnvakt och risker med att göra ytterdörren smart.","köpguide",["smart-lock","door-window-sensor"],["kopguide","lås","säkerhet","dorrar"],"Smarta lås kan vara praktiska, men de ska väljas mer försiktigt än lampor och knappar. Ytterdörren är kritisk. Mekanisk kvalitet, reservöppning och familjens rutiner är viktigast.",["Barnvakten får tidsbegränsad kod i stället för extra nyckel.","Dörrsensor visar om dörren är stängd även om låset är separat.","Familjen har alltid fysisk reservväg."],[["När det passar", "Smart lås passar bäst när nyckellogistik är ett återkommande problem."],["När du ska vänta", "Om låset är gammalt, dörren kärvar eller familjen är osäker: lös mekaniken först."],["Koddisciplin", "Tillfälliga koder ska tas bort när de inte behövs."],["Kombinera med dörrsensor", "Låst betyder inte alltid stängd. En dörrsensor kan ge bättre status."]]),
a("fryslarm-med-temperatursensor","Fryslarm med temperatursensor: rädda maten innan det är för sent","Så använder du enkel temperatursensor i frys, förråd eller källare.","guide",["temperature-sensor"],["guide","klimat","sensorer","frys"],"En temperatursensor i eller nära frysen är inte glamorös, men kan vara väldigt praktisk. Särskilt i förråd, garage eller källare där ingen märker att något blivit fel förrän långt senare.",["Frysen i förrådet blir för varm och skickar varning.","Källaren sjunker mot frostnivå och dashboarden visar tydligt larm.","Sommarstugans temperatur kollas utan att någon åker dit."],[["Placera rätt", "Alla sensorer klarar inte minusgrader inuti frysen. Ibland räcker det att mäta nära eller använda modell som tål miljön."],["Larma långsamt", "Skicka inte larm vid varje dörröppning. Larma om temperaturen är för hög för länge."],["Batteri i kyla", "Kyla kan påverka batteri. Kontrollera status oftare."],["Testa gränser", "Sätt gränsen så att familjen hinner agera innan maten är förstörd."]]),
a("smart-brevlada-dorrsensor","Smart brevlåda med dörrsensor","En enkel sensor kan säga när posten kommit utan kamera eller krånglig installation.","guide",["door-window-sensor"],["guide","dorrar","sensorer"],"En dörrsensor i brevlådan är ett typiskt litet smart hem-projekt: billigt, konkret och lätt att förstå. Det behövs ingen kamera, bara en signal när luckan öppnas.",["Dashboarden visar 'posten har kommit'.","En notis skickas bara en gång per dag.","Sensorn sitter skyddad från regn och testas innan den limmas fast."],[["Välj rätt sensor", "Sensor och magnet måste kunna sitta så att luckans rörelse registreras."],["Skydda mot väder", "Brevlådor kan vara kalla och fuktiga. Placera sensorn så torrt som möjligt."],["Undvik spam", "Skicka inte notis varje gång luckan rör sig om den kan blåsa."],["Bra familjenytta", "Barn kan se på skärmen om posten redan hämtats."]]),
a("smart-forrad-garage-sensorer","Förråd och garage: sensorer som ger koll utan kamera","Dörrsensor, temperatur och vattenlarm för utrymmen du inte tittar i varje dag.","guide",["door-window-sensor","temperature-sensor","water-leak-sensor"],["guide","forrad","garage","sensorer","klimat"],"Förråd och garage är bra platser för enkla sensorer eftersom problemen ofta upptäcks sent: öppen dörr, kyla, fukt eller vatten.",["Garageporten står öppen längre än tio minuter.","Förrådet blir för kallt för färg eller elektronik.","Vattenlarm i källarförråd reagerar innan kartonger blir blöta."],[["Dörr först", "En dörrsensor löser ofta det tydligaste problemet: står något öppet?"],["Temperatur för saker", "Mät där du förvarar sådant som kan skadas av kyla eller värme."],["Vatten i källare", "Källarutrymmen bör ha vattenlarm om det finns golvbrunn, rör eller tidigare fuktproblem."],["Kamera behövs sällan", "Börja med status. Kamera skapar mer integritets- och underhållsfrågor."]]),
a("integritet-smart-hem-familj","Integritet i smarta hem: vad ska barnfamiljer tänka på?","Kameror, mikrofoner, molntjänster och vad som bör hållas lokalt.","guide",["zigbee-hub","smart-button"],["guide","integritet","säkerhet","home-assistant"],"Ett smart hem samlar lätt fler signaler än man tänker på. För familjer är det viktigt att skilja på praktisk automation och övervakning.",["Familjen väljer knapp i hallen i stället för kamera.","Barnrum får inga mikrofonbaserade lösningar.","Lokala sensorer används för rutiner som inte behöver molnet."],[["Undvik kameror som första lösning", "Många vardagsproblem kan lösas med dörrsensor, knapp eller dashboard."],["Barnrum kräver extra eftertanke", "Teknik i barnrum ska vara begriplig och motiverad, inte dold."],["Konton och lösenord", "Använd starka konton och tvåfaktor där molntjänster behövs."],["Lokalt när det går", "Home Assistant och Zigbee kan minska mängden data som skickas utanför hemmet."]]),
a("backup-home-assistant-familj","Backup i Home Assistant: så slipper familjen teknikpanik","En enkel backup-rutin för hem där smarta funktioner faktiskt används.","guide",["zigbee-hub"],["guide","home-assistant","backup"],"När Home Assistant börjar styra riktiga vardagsrutiner blir backup viktigt. Inte för att allt ska vara perfekt, utan för att familjen inte ska tappa lampor, knappar och dashboards vid ett misstag.",["Backup tas innan större uppdatering.","En enkel lista visar vilka knappar som styr vad.","Vanliga lampor går fortfarande att tända manuellt."],[["Automatisk backup", "Se till att backup skapas regelbundet och gärna kopieras utanför enheten."],["Dokumentera det viktiga", "Skriv ner Zigbee-adapter, viktiga integrationer och vad som måste återställas först."],["Testa återställning", "En backup som aldrig testats är en gissning."],["Manuell fallback", "Familjen ska kunna leva hemma även om Home Assistant är nere en kväll."]]),
a("forbattra-zigbee-mesh-hemma","Förbättra Zigbee-mesh hemma: stabilare sensorer och knappar","Så placerar du hubb, routrar och lampor för färre tappade signaler.","guide",["zigbee-hub","smart-bulb","smart-plug"],["guide","zigbee","sensorer"],"Många Zigbee-problem handlar inte om dåliga sensorer utan om svagt mesh. Batteriprylar behöver fasta Zigbee-enheter som hjälper nätet.",["Knappen i hallen slutar tappa kontakt när en smart plug placeras nära.","Hubben flyttas bort från wifi-router och metallskåp.","Lampor och pluggar bygger mesh mellan våningar."],[["Hubben ska stå fritt", "Undvik att gömma hubben bakom router, tv eller metall."],["Fasta enheter hjälper", "Nätanslutna lampor och pluggar kan fungera som routrar i Zigbee-nätet."],["Batterisensorer routar inte", "Små sensorer sparar batteri och hjälper normalt inte andra enheter."],["Ändra en sak i taget", "Flytta hubb eller lägg till router och testa innan du byter allt."]]),
a("smarta-gardiner-barnrum","Smarta gardiner i barnrum: morgonljus och mörkläggning","När automatiska gardiner är praktiska och när de bara är dyrt lullull.","guide",["smart-blinds","smart-button"],["guide","barnrum","belysning","morgon"],"Smarta gardiner kan hjälpa med morgonljus och kvällsmörker, men de är ofta dyrare och mer mekaniska än lampor. Börja bara där problemet är tydligt.",["Rullgardinen öppnas lite på vardagsmorgnar.","Barnrummet mörkläggs automatiskt före läggning.","En knapp vid dörren stoppar gardinen manuellt."],[["Bra användning", "Morgonljus i mörka perioder och mörkläggning vid läggning är de tydligaste fallen."],["Kolla ljudnivå", "En högljudd motor i barnrum kan förstöra poängen."],["Manuell kontroll", "Gardinen måste kunna stoppas och styras utan app."],["Börja med ett rum", "Testa i ett rum innan du köper till hela hemmet."]]),
a("basta-smarta-gardiner-familj","Bästa smarta gardiner för familjer","Köpguide för rullgardinsmotorer, gardinskenor och automationer som faktiskt används.","köpguide",["smart-blinds","smart-button"],["kopguide","belysning","morgon","barnrum"],"Smarta gardiner kan vara vardagsnytta i rätt rum: barnrum, sovrum eller vardagsrum med stark sol. Men det är en kategori där felköp snabbt blir dyrt.",["Sovrummet får långsam öppning på vardagsmorgnar.","Vardagsrummet stänger för stark eftermiddagssol.","Barnrummet har knapp som alltid överstyr automatik."],[["Välj efter gardintyp", "Rullgardin, gardinskena och persienn kräver olika lösningar."],["Batteri eller sladd", "Batteri är enklare men kräver laddning. Sladd är stabilare men svårare att installera snyggt."],["Integration", "Kontrollera stöd för Home Assistant eller den hubb du redan använder."],["Säkerhet", "I barnrum är mekanisk säkerhet och snören viktigare än smarta funktioner."]]),
a("smart-hem-utan-abonnemang","Smart hem utan abonnemang: välj prylar med låg löpande kostnad","Undvik lösningar som ser billiga ut men kräver moln, hubbavgift eller extra tjänst.","guide",["zigbee-hub","smart-button","smart-bulb"],["guide","budget","home-assistant","zigbee"],"Ett smart hem ska inte kännas som ännu en prenumeration. Många funktioner går att få utan abonnemang om du väljer rätt typ av prylar och undviker onödiga molnberoenden.",["Zigbee-knappar fungerar utan månadsavgift.","Lokala automationer fortsätter även om en app ändrar villkor.","Familjen köper färre prylar men behåller kontrollen."],[["Läs innan köp", "Kolla om funktioner kräver premiumkonto eller molnlagring."],["Välj standarder", "Zigbee, Matter och lokal Home Assistant-styrning kan minska inlåsning."],["Kameror är vanlig fälla", "Många kameror kräver abonnemang för historik. Fråga om du verkligen behöver kamera."],["Billigt över tid", "En dyrare pryl utan abonnemang kan bli billigare efter ett år."]]),
a("matter-vs-zigbee-familj","Matter eller Zigbee för barnfamiljer?","Vad skillnaden betyder när du köper lampor, sensorer och knappar.","guide",["zigbee-hub","smart-bulb","smart-button"],["guide","matter","zigbee","kopguide"],"Matter och Zigbee blandas ofta ihop i köpråd. För familjen är den praktiska frågan enklare: kommer prylarna fungera stabilt med systemet du faktiskt använder?",["Zigbee-sensorer används för batterisnåla nattljus.","Matter-lampa köps där enkel plattformsstöd är viktigare.","Home Assistant samlar båda när stödet är moget."],[["Zigbee i korthet", "Zigbee är vanligt för batterisensorer, knappar och lampor. Det kräver ofta hubb eller adapter."],["Matter i korthet", "Matter ska göra kompatibilitet enklare mellan ekosystem, men allt stöd är inte lika moget."],["Köp inte på logga ensam", "Kontrollera verkligt stöd med din hubb och andra användares erfarenheter."],["Familjens prioritet", "Stabilitet, manuell kontroll och rimlig felsökning är viktigare än trendord."]]),
a("smarta-hem-for-laxa-och-fokus","Smart hem för läxa och fokus","Ljus, timer och störningsfria signaler för eftermiddag utan tjat.","guide",["smart-button","smart-bulb","tablet-wall"],["guide","rutiner","belysning","knappar"],"Läxläsning behöver inte mer skärm. Ofta räcker en tydlig startsignal, rätt ljus och en timer som inte känns som vuxentjat.",["En knapp på skrivbordet tänder fokusljus och startar 25 minuter.","Dashboarden visar bara läxa, paus och nästa aktivitet.","Lampan byter färg när det är dags för paus."],[["Gör starten fysisk", "En knapp är bättre än att öppna en app när barnet redan ska fokusera."],["Ljus som rumssignal", "Samma ljus varje gång hjälper kroppen förstå att det är fokusläge."],["Kort timer", "Börja med korta pass. För långa fokuspass blir bara ännu en konflikt."],["Avslut är viktigt", "Visa när passet är klart. Annars känns rutinen som oändlig."]]),
a("smart-hem-for-medicinpaminnelser","Smarta medicinpåminnelser hemma utan stress","Diskreta påminnelser för medicin, vitaminer eller återkommande rutiner.","guide",["smart-button","tablet-wall","smart-bulb"],["guide","notiser","rutiner","dashboard"],"Medicinpåminnelser ska vara tydliga men inte skambeläggande. Smarta hem kan hjälpa genom synliga signaler och enkel kvittens, men ska inte ersätta medicinsk rådgivning eller säkra rutiner.",["Köksskärmen visar en diskret rad vid rätt tid.","En knapp markerar att dosen är tagen.","Lampan blinkar inte, utan ändrar lugnt färg tills någon kvitterar."],[["Synligt där rutinen sker", "Placera signalen i kök, badrum eller annan plats där medicinen faktiskt tas."],["Kvittens", "En knapp kan markera klart och ta bort påminnelsen från dashboarden."],["Undvik höga larm", "Stressiga ljud gör att familjen vill stänga av systemet."],["Ha backup", "Viktiga mediciner ska ha en reservrutin om tekniken fallerar."]]),
a("smart-hem-for-familj-med-skiftarbete","Smart hem när familjen har skiftarbete","Rutiner som tar hänsyn till olika sovtider, lämningar och hämtningar.","guide",["smart-bulb","smart-button","tablet-wall"],["guide","rutiner","morgon","laggdags"],"Skiftarbete gör vanliga automationer svårare. Alla vaknar inte samtidigt och läggning kan betyda olika saker olika dagar.",["Nattljus tänds svagare när någon sover efter kvällsskift.","Dashboarden visar vem som hämtar utan att väcka den som sover.","Godmorgon-läge startas med knapp, inte fast tid."],[["Undvik fasta tider", "Knappstyrda lägen fungerar ofta bättre än klockslag när schemat varierar."],["Sovläge per person", "Om någon sover dagtid ska hall och kök kunna vara tystare."],["Dashboard för logistik", "Visa hämtning, mat och aktiviteter så färre frågor behöver ställas."],["Ljusscener", "Mjukt ljus kan hjälpa familjen röra sig utan att väcka den som sover."]]),
a("kopguide-smarta-hem-presenter","Köpguide: smarta hem-presenter som inte blir liggande","Små prylar som är lätta att ge bort och faktiskt använda.","köpguide",["smart-button","smart-bulb","water-leak-sensor","smart-plug"],["kopguide","budget","presenter"],"Smarta hem-presenter blir lätt fel om de kräver konto, hubb eller tålamod. Välj sådant som löser ett enkelt problem och går att förstå direkt.",["En smart plug gör en gammal adventslampa enkel att styra.","En vattenläckagesensor är tråkig men användbar under diskmaskinen.","En knapp blir genväg till kvällsläge."],[["Bäst som present", "Smarta pluggar, lampor och vattenlarm är lättare än avancerade hubbar."],["Undvik låsta ekosystem", "Ge inte bort något som bara passar ett system du inte vet att mottagaren har."],["Skriv användningsidé", "En lapp med tre konkreta exempel gör presenten mer användbar."],["Håll budgeten rimlig", "En dyr pryl som kräver installation blir ofta liggande."]]),
]

added=0
for item in new_articles:
    if item["slug"] not in existing:
        articles.append(item); existing.add(item["slug"]); added+=1
articles_path.write_text(json.dumps(articles,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
products_path.write_text(json.dumps(products,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
links_path.write_text(json.dumps(links,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print(f"added_articles={added}")
print(f"total_articles={len(articles)}")
print(f"products={len(products)}")
